server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/codex
    username: root
    password: 1715
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    username: the.codex.machina.ex.homini.team@gmail.com
    password: ybamjoklwbadkbdc
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update